id: 813d6be3d50546d0843bc7ed7a659bd9
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_178-Teaching_on_the_Aids_to_Enlightenment-v2
  language: en
  author: ''
  volume: {}
